export const CATEGORIES = [
  {
    id: 1,
    color: "#00aa00",
    icon: "account_balance",
    title: "Podatki",
  },
  {
    id: 1,
    color: "#00aaaa",
    icon: "directions_bus",
    title: "Transport",
  },
  {
    id: 1,
    color: "#aaaa00",
    icon: "local_airport",
    title: "Podróże",
  },
  {
    id: 1,
    color: "#055a00",
    icon: "shopping_cart",
    title: "Zakupy",
  },
  {
    id: 1,
    color: "#00001f",
    icon: "storefront",
    title: "Piekarnia",
  },
  {
    id: 1,
    color: "#aaaaaf",
    icon: "electric_bolt",
    title: "Prąd",
  },
  {
    id: 1,
    color: "#ffaa00",
    icon: "water_drop",
    title: "Woda",
  },
  {
    id: 1,
    color: "#ff1111",
    icon: "restaurant",
    title: "Eat out",
  },
  {
    id: 1,
    color: "#123456",
    icon: "local_bar",
    title: "Bar",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "lunch_dining",
    title: "Lunch",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "local_pizza",
    title: "Pizza",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "icecream",
    title: "Lody",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "music_note",
    title: "Muzyka",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "flight",
    title: "Samolot",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "health_and_safety",
    title: "Zdrowie",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "home",
    title: "Dom",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "handyman",
    title: "Naprawy",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "card_giftcard",
    title: "Prezenty",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "checkroom",
    title: "Ciuchy",
  },
  {
    id: 1,
    color: "#00aa00",
    icon: "question_mark",
    title: "Inne",
  },
];
